### PR TITLE
fix: improve perceived speed of preflight cert generation

### LINKED ISSUE #79: Pre-flight check cert generation refresh is slow (Add Wait/ Load state)
**Describe the bug**
Generating a certificate from the pre-flight check page, can take anywhere from several seconds to several minutes to update certificate state, causing users to either 1) think the app is broken and abandon it or 2) think that they need to regenerate (and click the button multiple times, leading to multiple certs being created).

**To Reproduce**
1. Revoke all certs
2. Start new deploy
3. Generate cert from preflight check page
4. Observe how long it takes to change from "no valid cert red state" to "valid cert, green state"

**Expected behavior**
Should refresh instantaneously (1-2secs) so that the user does not regenerate certificates and/ or doesn't refresh the page (which will cause SDL to be invalid) or assume that the product is broken and give up.

If it is not possible for Console to speed this up (because it is dependent on the RPC node responding after querying the blockchain) then we should AT LEAST add a wait/ loading state.

The specific page is the preflight check page (/new-deployment/akash-games/tetris/preflight-check) not the cert generation page, that needs some kind of loading state to let the user know that the app is waiting on the rpc node (and blockchain) to query the cert list and come back.

So from the state you have (no active certs) - leave that as-is, then go and deploy something (just pick fun & games | tetris for example) and then when you get there and see this page:

Screenshot 2023-03-25 at 10 11 49 AM

When you click generate cert the app will show no wait state but it is actually waiting on the new cert to be available on the blockchain. If you wait long enough or refresh the page, you'll see the state change. This is where we need the wait state

### PR DESCRIPTION
**Pull request by yshsaxena**
**Feature**: Added Progress Indicator for Better UX.
End to End Tested Till Deployment.

fixes #79

### CODE REVIEW

**Comment by anilmurty** [comment]
Thanks @yshsaxena !

File: web/src/pages/PreflightCheck.tsx [hunk 1]
```diff
@@ -31,6 +31,8 @@ export const PreflightCheck: React.FC<{}> = () => {
   const [isValidCert, setIsValidCert] = React.useState(false);
   const sdl = (values as { sdl: SDLSpec }).sdl;
   const [manifestVersion, setManifestVersion] = React.useState<Uint8Array>();
+  const [loading, setLoading] = React.useState(false);
+  const [showVarifiedCert, setShowVarifiedCert] = React.useState(false);
```
Comment (anilmurty) [inline web/src/pages/PreflightCheck.tsx:35]: minor typo: Varified s/be Verified (setShowVerified) but ok to leave since it is a variable :)

**Review by jtary — APPROVED** [review]

**Comment by jtary** [comment]
@yshsaxena thanks for the contribution :wave:
